/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HotelManagement.view;


import HotelManagement.Controller.CategoryController;
import HotelManagement.Controller.PackageController;
import HotelManagement.Controller.ReservationsController;
import HotelManagement.dto.ReservationsDto;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;


/**
 *
 * @author kavindi
 */
public class ResevationView extends javax.swing.JFrame {

    private ReservationsController RsvController;
    SimpleDateFormat dtFormat = new SimpleDateFormat("yyyy-MM-dd");   
    
    /**
     * Creates new form ResevationView
     */
    public ResevationView() {
        RsvController = new ReservationsController();
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labRnum2 = new javax.swing.JLabel();
        txtRmNo2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        labEnDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtStDate = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btSave = new javax.swing.JButton();
        labCustId = new javax.swing.JLabel();
        btUpdate = new javax.swing.JButton();
        txtCustId = new javax.swing.JTextField();
        btDelete = new javax.swing.JButton();
        labRnum = new javax.swing.JLabel();
        txtRmNo = new javax.swing.JTextField();
        labResNo = new javax.swing.JLabel();
        txtResNo = new javax.swing.JTextField();
        labCtId = new javax.swing.JLabel();
        txtCtId = new javax.swing.JTextField();
        labPcId = new javax.swing.JLabel();
        txtPcId = new javax.swing.JTextField();
        labStDate = new javax.swing.JLabel();
        txtEnDate = new javax.swing.JTextField();
        labAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        labAmount1 = new javax.swing.JLabel();
        btCalAmount = new javax.swing.JButton();
        btCalAmount1 = new javax.swing.JButton();

        labRnum2.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labRnum2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labRnum2.setText("Room No");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labEnDate.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labEnDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labEnDate.setText("End Date");

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel1.setText("Manage Reservatios ");

        btSave.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        btSave.setText("New Booking");
        btSave.setAlignmentY(0.0F);
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        labCustId.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labCustId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labCustId.setText("Customer ID");

        btUpdate.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        btUpdate.setText("Update");
        btUpdate.setAlignmentY(0.0F);
        btUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdateActionPerformed(evt);
            }
        });

        txtCustId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustIdActionPerformed(evt);
            }
        });

        btDelete.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        btDelete.setText("Cancel");
        btDelete.setAlignmentY(0.0F);
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });

        labRnum.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labRnum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labRnum.setText("Room No");

        labResNo.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labResNo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labResNo.setText("Reservation No");

        labCtId.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labCtId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labCtId.setText("Category Id");

        labPcId.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labPcId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labPcId.setText("Package Id");

        txtPcId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPcIdActionPerformed(evt);
            }
        });

        labStDate.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labStDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labStDate.setText("Start Date");

        txtEnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnDateActionPerformed(evt);
            }
        });

        labAmount.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labAmount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labAmount.setText("Amount");

        labAmount1.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        labAmount1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labAmount1.setText("Rs:");

        btCalAmount.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        btCalAmount.setText("Show Amount");
        btCalAmount.setAlignmentY(0.0F);
        btCalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalAmountActionPerformed(evt);
            }
        });

        btCalAmount1.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        btCalAmount1.setText("Search Resevation");
        btCalAmount1.setAlignmentY(0.0F);
        btCalAmount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalAmount1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labRnum, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRmNo)
                                .addGap(44, 44, 44)
                                .addComponent(labCtId, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCtId, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labPcId, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(txtPcId, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labEnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtEnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btCalAmount)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(labAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labStDate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtStDate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(labResNo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(4, 4, 4)
                                                .addComponent(txtResNo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(txtCustId)))
                                        .addGap(38, 38, 38)
                                        .addComponent(btCalAmount1)
                                        .addGap(113, 113, 113)))))
                        .addGap(6, 6, 6)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(199, 199, 199))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCalAmount1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labResNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtResNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labRnum, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRmNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labCtId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCtId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labPcId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPcId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labEnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labStDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        svaeResevation();
    }//GEN-LAST:event_btSaveActionPerformed

    private void btUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdateActionPerformed
        updateResevation();
    }//GEN-LAST:event_btUpdateActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        cancelResevation();
    }//GEN-LAST:event_btDeleteActionPerformed

    private void txtCustIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustIdActionPerformed

    private void txtPcIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPcIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPcIdActionPerformed

    private void btCalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalAmountActionPerformed
        CalAmount();        // TODO add your handling code here:
    }//GEN-LAST:event_btCalAmountActionPerformed

    private void txtEnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnDateActionPerformed

    private void btCalAmount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalAmount1ActionPerformed
            searchResevation();
    }//GEN-LAST:event_btCalAmount1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalAmount;
    private javax.swing.JButton btCalAmount1;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labAmount;
    private javax.swing.JLabel labAmount1;
    private javax.swing.JLabel labCtId;
    private javax.swing.JLabel labCustId;
    private javax.swing.JLabel labEnDate;
    private javax.swing.JLabel labPcId;
    private javax.swing.JLabel labResNo;
    private javax.swing.JLabel labRnum;
    private javax.swing.JLabel labRnum2;
    private javax.swing.JLabel labStDate;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCtId;
    private javax.swing.JTextField txtCustId;
    private javax.swing.JTextField txtEnDate;
    private javax.swing.JTextField txtPcId;
    private javax.swing.JTextField txtResNo;
    private javax.swing.JTextField txtRmNo;
    private javax.swing.JTextField txtRmNo2;
    private javax.swing.JTextField txtStDate;
    // End of variables declaration//GEN-END:variables

   
    

    private void searchResevation() {
        try {
            String id = txtResNo.getText();
            ReservationsDto RsvDto = RsvController.searchResevation(id);
          //  SimpleDateFormat dtFormat = new SimpleDateFormat("yyyy-MM-dd");
            if (RsvDto != null) {
                txtResNo.setText(RsvDto.getResNo());
                txtCustId.setText(RsvDto.getCustID());
                txtRmNo.setText(RsvDto.getRoomNo());
                txtCtId.setText(RsvDto.getCtgID());
                txtPcId.setText(RsvDto.getPackageID());
                txtStDate.setText(dtFormat.format(RsvDto.getStartDate()));
                txtEnDate.setText(dtFormat.format(RsvDto.getEndDate()));
                txtAmount.setText(Double.toString(RsvDto.getAmount()));
            }
            else{
                JOptionPane.showMessageDialog(this,"Resevation Not Found");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ResevationView.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(this,ex);
        }
    }

    private void svaeResevation() {
        
        try {
            
            /*     SimpleDateFormat time = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"); */
            LocalDateTime time = LocalDateTime.now();
            ReservationsDto RsvDto = new ReservationsDto(
                    txtResNo.getText(),
                    txtCustId.getText(),
                    txtRmNo.getText(),
                    txtCtId.getText(),
                    txtPcId.getText(),
                    dtFormat.parse(txtStDate.getText()),
                    dtFormat.parse(txtEnDate.getText()),
                    Double.parseDouble(txtAmount.getText()),
                    time);
            String rsp = RsvController.saveResevation(RsvDto);
            JOptionPane.showMessageDialog(this, rsp);
            clearData();
        } catch (Exception ex) {
            Logger.getLogger(ResevationView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex);
        }

       
    }

    private void CalAmount() {
       
        try {
            Date std = dtFormat.parse(txtStDate.getText());
            Date end = dtFormat.parse(txtEnDate.getText());
            Double amount = RsvController.calAmount(txtCtId.getText(), txtPcId.getText(), std, end);
            if(amount > 0){
                 txtAmount.setText(Double.toString(amount));
            }
            else {
               JOptionPane.showMessageDialog(this,"Enter Valaid Dates"); 
            }

        } catch (Exception ex) {
            Logger.getLogger(ResevationView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex); 
        }
    }

    private void clearData() {
      //  Date defaultDate = new Date();
        txtResNo.setText("");
        txtCustId.setText("");
        txtRmNo.setText("");
        txtCtId.setText("");
        txtPcId.setText("");
        txtStDate.setText("");
        txtEnDate.setText("");
        txtAmount.setText("");

    }

    private void updateResevation() {
        try {
            String id = txtResNo.getText();
            CalAmount();
            ReservationsDto prevouisDto = RsvController.searchResevation(id);
            ReservationsDto newDto = new ReservationsDto(
                    txtResNo.getText(),
                    txtCustId.getText(),
                    txtRmNo.getText(),
                    txtCtId.getText(),
                    txtPcId.getText(),
                    dtFormat.parse(txtStDate.getText()),
                    dtFormat.parse(txtEnDate.getText()),
                    Double.parseDouble(txtAmount.getText()),
                    prevouisDto.getTime());
            
            String rsp = RsvController.updateResevation(newDto);
            JOptionPane.showMessageDialog(this,rsp);
            clearData();
        } catch (Exception ex) {
            Logger.getLogger(ResevationView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex);
        }
        
    }

    private void cancelResevation() {
        try {
            String id = txtResNo.getText();
            String rsp = RsvController.cancelResevation(id);
            JOptionPane.showMessageDialog(this,rsp);
            JOptionPane.showMessageDialog(this,rsp);
            clearData();
        } catch (Exception ex) {
            Logger.getLogger(ResevationView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,ex);
        }
    }


}
